export const reportFormStyles = {
  root: `min-h-screen bg-[#FAF9F6] p-6`,
  wrap: `max-w-[900px] mx-auto`,
  topbar: `bg-[#A13D3D] text-[#E9B44C] p-3 rounded-lg text-center font-bold mb-4 shadow-md`,
  card: `bg-white p-6 rounded-xl shadow-lg`,
  heading: `text-[#A13D3D] text-2xl font-bold mb-2`,
  lead: `text-[#666666] mb-4`,
  row: `flex flex-col md:flex-row gap-3 mb-3`,
  col: `flex-1`,
  label: `text-sm text-gray-700 mb-1.5 font-semibold`,
  required: `text-[#b00020]`,
  small: `text-xs text-[#666666] mt-1.5`,
  note: `mt-3 p-2.5 border-l-4 border-[#E9B44C] bg-[#fffaf0] rounded-md text-[#5b3f00] text-sm`,
  result: `mt-4 p-3 rounded-lg bg-[#f3fff0] border-l-6 border-[#2f8a3a] text-[#1f5d2b]`,
  filesList: `mt-2 text-sm`,
  error: `text-[#b00020] text-xs mt-1.5`,
  searchRow: `flex flex-col sm:flex-row gap-3 max-w-md mx-auto mb-6`,
  noteBox: `mt-3 p-3 border-l-4 border-[#E9B44C] bg-[#fffaf0] rounded-md text-[#5b3f00] text-sm`,
  notFoundBox: `mt-4 p-4 rounded-lg border-l-4 border-[#b00020] bg-[#fff5f5] text-[#5b0000]`,
  statusCard: `bg-[#fff8f0] border border-[#f0e0c2] rounded-xl`,
  statusTitle: `text-lg font-semibold text-[#4a2a2a]`,
  statusText: `text-sm text-[#555555]`,
  infoGrid: `grid grid-cols-1 md:grid-cols-2 gap-4 text-sm mt-4`,
  value: `text-[#555555]`,
  progressTrack: `w-full bg-[#eee] rounded-full h-2.5`,
  progressFill: `h-2.5 rounded-full bg-[#A13D3D]`,
  sectionCard: `border border-[#f0e0c2] rounded-xl`,
  sectionTitle: `flex items-center gap-2 text-[#4a2a2a]`,
  smallText: `text-sm text-[#666666]`
};